-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["Apple_00"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "apple", density = 2, friction = 0.5, bounce = 0.2, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   5, -27.5  ,  -13, -27.5  ,  -6, -36.5  ,  6, -36.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "apple", density = 2, friction = 0.5, bounce = 0.2, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -6, -36.5  ,  -13, -27.5  ,  -12, -39.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "apple", density = 2, friction = 0.5, bounce = 0.2, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -28, -20.5  ,  5, -27.5  ,  22, -25.5  ,  37, 2.5  ,  3, 36.5  ,  -16, 36.5  ,  -32, 14.5  ,  -41, -8.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "apple", density = 2, friction = 0.5, bounce = 0.2, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3, 36.5  ,  37, 2.5  ,  22, 32.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "apple", density = 2, friction = 0.5, bounce = 0.2, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   37, 2.5  ,  22, -25.5  ,  34, -14.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "apple", density = 2, friction = 0.5, bounce = 0.2, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   5, -27.5  ,  -28, -20.5  ,  -13, -27.5  }
                    }
                    
                    
                    
		}
		
		, 
		["Apple_01"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "apple", density = 2, friction = 0.5, bounce = 0.2, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   5.5, -26  ,  -16.5, -30  ,  -6.5, -39  ,  6.5, -39  }
                    }
                     ,
                    {
                    pe_fixture_id = "apple", density = 2, friction = 0.5, bounce = 0.2, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   18.5, -5  ,  5.5, -26  ,  20.5, -29  ,  33.5, -14  }
                    }
                     ,
                    {
                    pe_fixture_id = "apple", density = 2, friction = 0.5, bounce = 0.2, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   12.5, 35  ,  -14.5, 35  ,  -33.5, 9  ,  -39.5, -11  ,  -16.5, -30  ,  24.5, 25  }
                    }
                     ,
                    {
                    pe_fixture_id = "apple", density = 2, friction = 0.5, bounce = 0.2, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   5.5, -26  ,  18.5, -5  ,  14.5, 11  ,  -16.5, -30  }
                    }
                    
                    
                    
		}
		
		, 
		["Apple_02"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "apple", density = 2, friction = 0.5, bounce = 0.2, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   5, -24.5  ,  -7, -23.5  ,  -6, -37.5  ,  7, -37.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "apple", density = 2, friction = 0.5, bounce = 0.2, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -24, -25.5  ,  -7, -23.5  ,  -19, -1.5  ,  -36, -11.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "apple", density = 2, friction = 0.5, bounce = 0.2, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -14, 18.5  ,  13, 10.5  ,  25, 26.5  ,  18, 36.5  ,  -15, 37.5  ,  -23, 27.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "apple", density = 2, friction = 0.5, bounce = 0.2, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   13, 10.5  ,  -14, 18.5  ,  -19, -1.5  ,  5, -24.5  ,  17, -28.5  ,  33, -16.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "apple", density = 2, friction = 0.5, bounce = 0.2, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   5, -24.5  ,  -19, -1.5  ,  -7, -23.5  }
                    }
                    
                    
                    
		}
		
		, 
		["Ball"] = {
                    
                    
                    
                    {
                    pe_fixture_id = "ball", density = 1, friction = 0.1, bounce = 0.9, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    radius = 29.069
                    }
                    
                    
		}
		
		, 
		["Duck"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "body", density = 5, friction = 1, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   60, 19  ,  33, 16  ,  49, 9  ,  70, 2  }
                    }
                     ,
                    {
                    pe_fixture_id = "body", density = 5, friction = 1, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   68, 27  ,  21, 67  ,  7, 17  ,  33, 16  ,  60, 19  ,  71, 21  }
                    }
                     ,
                    {
                    pe_fixture_id = "body", density = 5, friction = 1, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   49, 9  ,  33, 16  ,  48, -5  }
                    }
                     ,
                    {
                    pe_fixture_id = "body", density = 5, friction = 1, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -17, -2  ,  7, 17  ,  21, 67  ,  -3, 67  ,  -28, 45  }
                    }
                     ,
                    {
                    pe_fixture_id = "body", density = 5, friction = 1, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   32, -44  ,  24, -45  ,  -15, -63  ,  8, -67  }
                    }
                     ,
                    {
                    pe_fixture_id = "body", density = 5, friction = 1, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -15, -63  ,  24, -45  ,  7, 17  ,  -17, -2  ,  -32, -44  }
                    }
                     ,
                    {
                    pe_fixture_id = "body", density = 5, friction = 1, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   7, 17  ,  24, -45  ,  29, -26  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "beak", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -65, -31  ,  -66, -50  ,  -33, -41  ,  -22, -8  }
                    }
                    
                    
                    
		}
		
		, 
		["Floor"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "floor", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   314.5, 89  ,  236.5, -39  ,  313.5, -229  }
                    }
                     ,
                    {
                    pe_fixture_id = "floor", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   42.5, 89  ,  -1.5, -34  ,  236.5, -39  ,  314.5, 89  }
                    }
                     ,
                    {
                    pe_fixture_id = "floor", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   42.5, 89  ,  -313.5, 89  ,  -236.5, -35  ,  -120.5, -38  ,  -1.5, -34  }
                    }
                     ,
                    {
                    pe_fixture_id = "floor", density = 2, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -236.5, -35  ,  -313.5, 89  ,  -312.5, -224  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

