-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["drink"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "drink", density = 1, friction = 0.2, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 5 },
                    shape = {   -1.5, -32.5  ,  -6.5, 77.5  ,  -17.5, 73.5  ,  -28.5, -22.5  ,  -25.5, -30.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "drink", density = 1, friction = 0.2, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 5 },
                    shape = {   38, -21  ,  28, 67  ,  24, 76  ,  -6.5, 77.5  ,  -1.5, -32.5  ,  8.5, -33.5  ,  36.5, -29.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "straw", density = 2, friction = 0.1, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -25.5, -88  ,  2.5, -63  ,  -3.5, -62  ,  -31.5, -85  ,  -29.5, -88.1666717529297  }
                    }
                     ,
                    {
                    pe_fixture_id = "straw", density = 2, friction = 0.1, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2.5, -33  ,  -3.5, -62  ,  2.5, -63  ,  7.5, -34  }
                    }
                    
                    
                    
		}
		
		, 
		["hamburger"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "top", density = 2, friction = 0.3, bounce = 0.5, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -36.6060609817505, -19.9393920898438  ,  -19, -29.5  ,  21, -29.5  ,  41.2348480224609, -23.1590881347656  ,  48, -9.5  ,  16.4242401123047, -3.84090805053711  ,  -17.4772758483887, -2.70454406738281  ,  -44, -6.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "bottom", density = 2, friction = 0.6, bounce = 0.3, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   4, 33.8333332538605  ,  -35, 30.5  ,  -36, 19.5  ,  44, 18.5  ,  44, 30.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "beef", density = 2, friction = 0, bounce = 0.8, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -37, 15.5  ,  -43, 1.5  ,  43, -1.5  ,  44, 15.5  }
                    }
                    
                    
                    
		}
		
		, 
		["hotdog"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "hotdog", density = 2, friction = 0.2, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 65535, groupIndex = 0 },
                    shape = {   40.5, -25.5  ,  0, 28  ,  -30, 29  ,  -42, 26  ,  -8, -20  ,  29, -34  ,  37, -33  }
                    }
                     ,
                    {
                    pe_fixture_id = "hotdog", density = 2, friction = 0.2, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 65535, groupIndex = 0 },
                    shape = {   -57.5, -2.5  ,  -50, -13  ,  -8, -20  ,  -42, 26  ,  -56.5, 13.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "hotdog", density = 2, friction = 0.2, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 65535, groupIndex = 0 },
                    shape = {   58.5, -7.5  ,  52.5, 1.5  ,  30, 18  ,  0, 28  ,  40.5, -25.5  ,  59.5, -15.5  }
                    }
                    
                    
                    
		}
		
		, 
		["icecream"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "ice", density = 3, friction = 0.2, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   59.5, -32  ,  36, -7.5  ,  30, -8.5  ,  47, -33.5  ,  56, -40.5  ,  57, -40.5  ,  60.5, -38  }
                    }
                     ,
                    {
                    pe_fixture_id = "ice", density = 3, friction = 0.2, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   0, -23.5  ,  3.5, -18  ,  -11, -16.5  ,  -8, -22.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "ice", density = 3, friction = 0.2, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   39.5, 16  ,  29.5, 27  ,  13, 37.5  ,  -29, 37.5  ,  -37, -13.5  ,  36, -7.5  ,  42.5, 0  }
                    }
                     ,
                    {
                    pe_fixture_id = "ice", density = 3, friction = 0.2, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   4, -30.5  ,  3.5, -18  ,  0, -23.5  ,  1.5, -30  }
                    }
                     ,
                    {
                    pe_fixture_id = "ice", density = 3, friction = 0.2, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   7.5, -13  ,  -21, -12.5  ,  -11, -16.5  ,  3.5, -18  }
                    }
                     ,
                    {
                    pe_fixture_id = "ice", density = 3, friction = 0.2, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   -56, -3.5  ,  -37, -13.5  ,  -29, 37.5  ,  -51, 23.5  ,  -58, 12.5  ,  -59.5, 2  }
                    }
                     ,
                    {
                    pe_fixture_id = "ice", density = 3, friction = 0.2, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   30, -8.5  ,  -21, -12.5  ,  7.5, -13  }
                    }
                     ,
                    {
                    pe_fixture_id = "ice", density = 3, friction = 0.2, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   36, -7.5  ,  -21, -12.5  ,  30, -8.5  }
                    }
                    
                    
                    
		}
		
		, 
		["icecream2"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "ice", density = 1, friction = 0.2, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   -0.5, -40  ,  -4.5, 22  ,  -13, 22.5  ,  -22, 16.5  ,  -22, -31.5  ,  -10.5, -44  }
                    }
                     ,
                    {
                    pe_fixture_id = "ice", density = 1, friction = 0.2, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   6, 45.5  ,  6, 21.5  ,  14.5, 22  ,  15, 44.5  ,  11.5, 47  }
                    }
                     ,
                    {
                    pe_fixture_id = "ice", density = 1, friction = 0.2, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   6, 21.5  ,  2, 19.5  ,  7.5, -45  ,  8.5, -45  ,  20, -29.5  ,  20, 18.5  ,  14.5, 22  }
                    }
                     ,
                    {
                    pe_fixture_id = "ice", density = 1, friction = 0.2, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   -13, 22.5  ,  -4.5, 22  ,  -6, 46.5  ,  -12.5, 47  }
                    }
                     ,
                    {
                    pe_fixture_id = "ice", density = 1, friction = 0.2, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   7.5, -45  ,  2, 19.5  ,  -4.5, 22  ,  -0.5, -40  }
                    }
                    
                    
                    
		}
		
		, 
		["icecream3"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "cream", density = 2, friction = 0.2, bounce = 0.5, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   11, -40.5  ,  -19.5, -10  ,  -23.5, -12  ,  -23.5, -28  ,  -18.5, -37  ,  0, -49.5  ,  1, -49.5  ,  13, -48.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "cream", density = 2, friction = 0.2, bounce = 0.5, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   -19.5, -10  ,  11, -40.5  ,  18.5, -30  ,  22.5, -16  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "wafer", density = 2, friction = 0.4, bounce = 0.1, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   1, 55  ,  -15, -9  ,  15, -12  }
                    }
                    
                    
                    
		}
		
		, 
		["orange"] = {
                    
                    
                    
                    {
                    pe_fixture_id = "fruit", density = 2, friction = 0.2, bounce = 0.5, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    radius = 26.019
                    }
                    
                    
		}
		
		, 
		["bar"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "floor", density = 2, friction = 0.3, bounce = 0.4, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -160, -40  ,  160, -40  ,  160, 41  ,  -160, 41  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

